### ISSUE TITLE
Bash Script for Migrations

### ISSUE THREAD

**Issue by Kironb** [HackRU/mentorq-backend#2]
Setup a basic script to run all of the migrations necessary for our mentorq backend

**Comment by Anarav** [comment]
With the addition of the Docker image cbfbfbe7d54697a6229a199a1345fdbbf2ab3553 and the deployment of prod and dev environments 3e2d78b74f2a38f5a2bb97f71ff5400b1a3805be, a script doesn't seem necessary.

Theoretically, as long as migration files are committed appropriately, migrations just require one command `python manage.py migrate`
